### ISSUE TITLE
Deposit[205#]-Error Log

### ISSUE THREAD

**Issue by CloudS3c** [AlterRSPS/Alter#7]
Logger-message: [Command: cmd=obank, args=[]] , client: [Client{login_username=145, username=145, channel=[id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594]}]
[21:43:46.969 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 201.
[21:43:47.289 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 246.
[21:43:47.970 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 19.
[21:43:48.309 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 253.
[21:43:48.791 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 136.
[21:43:49.189 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 76.
[21:43:49.651 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 163.
[21:43:50.069 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 134.
[21:43:50.350 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 180.
[21:43:50.930 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 245.
Logger-message: [Update appearance: gender=MALE, appearance=[12, 3, 56, 31, 104, 34, 37], colors=[187, 22, 178, 23, 165]] , client: [Client{login_username=145, username=145, channel=[id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594]}]
[21:43:51.231 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 6.
[21:43:51.510 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 252.
Logger-message: [Update appearance: gender=MALE, appearance=[10, 3, 136, 127, 130, 38, 50], colors=[39, 121, 8, 33, 230]] , client: [Client{login_username=145, username=145, channel=[id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594]}]
[21:43:51.910 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 176.
[21:43:52.931 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 244.
[21:43:53.972 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 236.
[21:43:54.131 ERROR] GameService          | Error with task MessageHandlerTask.
java.lang.ArrayIndexOutOfBoundsException: Index 10284 out of bounds for length 2048
	at gg.rsmod.game.model.PawnList.get(PawnList.kt:24) ~[main/:?]
	at gg.rsmod.game.message.handler.OpPlayer6Handler.handle(OpPlayer6Handler.kt:28) ~[main/:?]
	at gg.rsmod.game.message.handler.OpPlayer6Handler.handle(OpPlayer6Handler.kt:15) ~[main/:?]
	at gg.rsmod.game.system.GameSystem.handleMessages(GameSystem.kt:57) ~[main/:?]
	at gg.rsmod.game.model.entity.Client.handleMessages(Client.kt:93) ~[main/:?]
	at gg.rsmod.game.task.MessageHandlerTask$execute$1.invoke(MessageHandlerTask.kt:17) ~[main/:?]
	at gg.rsmod.game.task.MessageHandlerTask$execute$1.invoke(MessageHandlerTask.kt:12) ~[main/:?]
	at gg.rsmod.game.model.PawnList.forEach(PawnList.kt:36) ~[main/:?]
	at gg.rsmod.game.task.MessageHandlerTask.execute(MessageHandlerTask.kt:15) ~[main/:?]
	at gg.rsmod.game.service.GameService.cycle(GameService.kt:227) [main/:?]
	at gg.rsmod.game.service.GameService.access$cycle(GameService.kt:33) [main/:?]
	at gg.rsmod.game.service.GameService$init$1.invoke(GameService.kt:129) [main/:?]
	at gg.rsmod.game.service.GameService$init$1.invoke(GameService.kt:33) [main/:?]
	at gg.rsmod.game.service.GameService$sam$java_lang_Runnable$0.run(GameService.kt) [main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[21:43:54.250 WARN ] GamePacketDecoder    | Channel [id: 0x6efc305c, /127.0.0.1:49320 => /127.0.0.1:43594] sent message with no valid metadata: 135.

**Comment by CloudS3c** [comment]
Packet: REFLECTION_CHECK_REPLY had same opcode as IfBtn[12]. Fixed.
